In [1]:
import pandas as pd
import scipy 
import numpy as np
from scipy import stats 

In [2]:
#Assignment1 
q1 = pd.read_csv("Cutlets.csv")

In [3]:
q1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35 entries, 0 to 34
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Unit A  35 non-null     float64
 1   Unit B  35 non-null     float64
dtypes: float64(2)
memory usage: 688.0 bytes


In [4]:
q1.describe()

Unit A     Unit B
count  35.000000  35.000000
mean    7.019091   6.964297
std     0.288408   0.343401
min     6.437600   6.038000
25%     6.831500   6.753600
50%     6.943800   6.939900
75%     7.280550   7.195000
max     7.516900   7.545900

In [9]:
 #assignment 2 
    
q2=pd.read_csv("LabTAT.csv") 

In [6]:
q2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laboratory 1  120 non-null    float64
 1   Laboratory 2  120 non-null    float64
 2   Laboratory 3  120 non-null    float64
 3   Laboratory 4  120 non-null    float64
dtypes: float64(4)
memory usage: 3.9 KB


In [7]:
q2.describe()

Laboratory 1  Laboratory 2  Laboratory 3  Laboratory 4
count    120.000000    120.000000    120.000000     120.00000
mean     178.361583    178.902917    199.913250     163.68275
std       13.173594     14.957114     16.539033      15.08508
min      138.300000    140.550000    159.690000     124.06000
25%      170.335000    168.025000    188.232500     154.05000
50%      178.530000    178.870000    199.805000     164.42500
75%      186.535000    189.112500    211.332500     172.88250
max      216.390000    217.860000    238.700000     205.18000

In [8]:
q2.std()

Laboratory 1    13.173594
Laboratory 2    14.957114
Laboratory 3    16.539033
Laboratory 4    15.085080
dtype: float64

In [10]:
(180-178.36)/(13.17/np.sqrt(120))

1.364107812161678

In [12]:
stats.t.pdf(1.36,df=119)

0.15779830730448866

In [11]:
(180-178.9)/(14.95/np.sqrt(120))

0.8060131281012437

In [13]:
stats.t.pdf(0.80,df=119)

0.28855666846605266

In [18]:
(200-199)/(16.5/np.sqrt(120))

0.6639061303092922

In [19]:
stats.t.pdf(0.66,df=119)

0.31973312981391117

In [21]:
(165-163.5)/(15/np.sqrt(120))

1.0954451150103321

In [ ]:
stats.t.pdf(0.31,df=119)

In [48]:
q3=pd.read_csv("BuyerRatio.csv") #assignment 3

In [10]:
q3.describe()


East         West        North       South
count    2.000000     2.000000     2.000000    2.000000
mean   242.500000   832.500000   743.500000  410.000000
std    272.236111   976.514465   866.205807  480.832611
min     50.000000   142.000000   131.000000   70.000000
25%    146.250000   487.250000   437.250000  240.000000
50%    242.500000   832.500000   743.500000  410.000000
75%    338.750000  1177.750000  1049.750000  580.000000
max    435.000000  1523.000000  1356.000000  750.000000

In [22]:
(250-242)/(272.23/np.sqrt(2))

0.04155937442230746

In [42]:



stats.t.pdf(0.04,df=1)

0.31780140393749073

In [44]:
(850-832.5)/(976.5/np.sqrt(2))

0.02534432907478665

In [46]:
stats.t.pdf(0.02,df=1)

0.31818261313853535

In [50]:
(750-743.5)/(866.2/np.sqrt(2))

0.010612316041820731

In [53]:
stats.t.pdf(0.0106,df=1)

0.3182741249031167

In [55]:
(415-410)/(480.83/np.sqrt(2))

0.014705962215056207

In [57]:
stats.t.pdf(0.014,df=1)

0.318247509671895

In [61]:
q4=pd.read_csv("Costomer+OrderForm.csv")

In [59]:
q4.describe()

NameError: name 'q4' is not defined

In [71]:
q4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Phillippines  300 non-null    object
 1   Indonesia     300 non-null    object
 2   Malta         300 non-null    object
 3   India         300 non-null    object
dtypes: object(4)
memory usage: 9.5+ KB


In [11]:
q41 = pd.read_excel("Costomer-OrderForm-_1_.xlsx")
q41

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [5]:
 q41=pd.crosstab(q41["India"],q41["Malta"])
q41

Malta       Defective  Error Free
India                            
Defective           0          20
Error Free         31         249

In [6]:
Chisquares_results=scipy.stats.chi2_contingency(q41)

In [7]:
Chisquares_results

(1.419106436194816,
 0.23355053527979247,
 1,
 array([[  2.06666667,  17.93333333],
        [ 28.93333333, 251.06666667]]))

In [15]:
 q42=pd.crosstab(q41["Phillippines"],q41["Indonesia"])
    

In [17]:
q42

Indonesia     Defective  Error Free
Phillippines                       
Defective             2          27
Error Free           31         240

In [27]:
Chisquares_results=scipy.stats.chi2_contingency(q42)

In [28]:
Chisquares_results1

(0.1856391005881107,
 0.6665712150680798,
 1,
 array([[  3.19,  25.81],
        [ 29.81, 241.19]]))

In [26]:
 q43=pd.crosstab(q41["India"],q41["Phillippines"])
q43

Phillippines  Defective  Error Free
India                              
Defective             2          18
Error Free           27         253

In [31]:
Chisquares_results2=scipy.stats.chi2_contingency(q43)

In [33]:
Chisquares_results2

(0.11520004362605206,
 0.7342998926385209,
 1,
 array([[  1.93333333,  18.06666667],
        [ 27.06666667, 252.93333333]]))

In [35]:
 q44=pd.crosstab(q41["Indonesia"],q41["Malta"])


In [37]:
q44

Malta       Defective  Error Free
Indonesia                        
Defective           9          24
Error Free         22         245

In [39]:
Chisquares_results3=scipy.stats.chi2_contingency(q44)

In [40]:
Chisquares_results3

(9.52050868943337,
 0.0020318825161213722,
 1,
 array([[  3.41,  29.59],
        [ 27.59, 239.41]]))